### ISSUE TITLE
kind 9 is already in use

### ISSUE THREAD

**Issue by melvincarvalho** [lovvtide/nostr-torrent#1]
https://nostrdata.github.io/kinds/

Not a show stopper, but you might want to choose another number

**Comment by lovvtide** [comment]
How did I not notice that 🤦 Thanks. We'll have to use a different number.

**Comment by lovvtide** [comment]
If we end up going with a new event kind (see https://github.com/lovvtide/nostr-torrent/issues/2) it should be kind `2001`
- Because BitTorrent protocol was created in 2001
- Because 2001 is within the range reserved for regular events
- Because Space Odyssey ¯\_(ツ)_/¯
